pretrained_model_path: "google/vit-base-patch16-224"
num_labels: 1
batch_size: 64
metric: "macro"
output_dir: "./training_outputs"
epochs: 1
lr: 0.01
model_output_dir: "./models"
reproducible_experiment: False
seed: 15
light_weight: True
test: False
cloud: False
