pretrained_model_path: "google/vit-base-patch16-224"
num_labels: 40
batch_size: 64
metric: "macro"
output_dir: "./training_outputs"
epochs: 5
lr: 0.01
model_output_dir: "./models"
reproducible_experiment: True
seed: 15
light_weight: True
