steps:
- name: Checkout
  uses: actions/checkout@v2
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/dtumlops-335110/testing', 'dockerfiles/train_model']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dtumlops-335110/testing']