steps:
# Setup Env
- name: python
  entrypoint: bash
  args: ['-c', 'pip install -U dvc dvc[gs]; dvc pull; sudo apt-get unzip; cd data/; unzip testing.zip; cd ..;']

# Build Train 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/project-mloperations/test/trainer', '-f', 'dockerfiles/train.dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/project-mloperations/test/trainer']

# Build Predict Server
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/project-mloperations/test/predict_server', '-f', 'dockerfiles/server.dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/project-mloperations/test/predict_server']