steps:
- id: 'setup-environment'
  name: python
  entrypoint: bash
  args: ['-c', 'pip install -U dvc dvc[gs]; dvc pull; sudo apt-get unzip; cd data/; unzip testing.zip; cd ..;']

- id: 'build-trainer-image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/project-mloperations/test/trainer', '-f', 'dockerfiles/train.dockerfile', '.']
- id: 'push-trainer-image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/project-mloperations/test/trainer']

- id: 'build-predict-image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/project-mloperations/test/predict_server', '-f', 'dockerfiles/server.dockerfile', '.']
- id: 'push-predict-image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/project-mloperations/test/predict_server']