steps:
- name: python
  entrypoint: bash
  args: ['-c', 'pip install -U dvc dvc[gs]; dvc pull; sudo apt-get unzip; cd data/; unzip testing.zip;']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/dtumlops-335110/testing', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dtumlops-335110/testing']