wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705362116.86669
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 50
      - 51
      - 53
      - 55
      - 71
      - 100
      - 105
      3:
      - 23
      4: 3.11.5
      5: 0.16.2
      6: 4.36.2
      8:
      - 5
      13: linux-x86_64
