name: "Run tests"

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ matrix.os }}-py${{ matrix.python-version }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ matrix.os }}-py${{ matrix.python-version }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
        pip install -e .
        sudo apt-get install unzip
    - name: Auth gcloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCLOUD_BUCKET_SERVICE_ACCOUNT_KEY }}'
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    - uses: iterative/setup-dvc@v1

    - name: Get data
      run: |
        dvc pull data/testing.zip.dvc
        dvc pull models.dvc
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

    - name: Unzip data
      run: |
        cd data
        unzip testing.zip
        unzip training.zip
        cd ..

    - name: Test with pytest and generate Report
      run: |
        coverage run -m pytest tests/
        coverage xml -o coverage.xml -i

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: coverage.xml
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
